### ISSUE TITLE
Error on archived repositories

### ISSUE THREAD

**Issue by carstingaxion** [actions-automation/organization-labels#4]
Hello @mbestavros and thank you for sharing this nice action with the world.

I used your action for a while without any problems, until I archived one of my repositories. Now the actions runs fine until it *hits* the archived repo.

```log
 File "/home/runner/work/_actions/actions-automation/manage-your-labels/main/src/mirror-labels", line 177, in <module>
    githubgql.graphql(CREATE_LABEL, token=token, accept="application/vnd.github.bane-preview+json", input={
  File "/home/runner/.local/lib/python3.10/site-packages/githubgql/githubgql.py", line 125, in graphql
    raise GraphQLError(data["errors"])
githubgql.githubgql.GraphQLError: [{'type': 'UNPROCESSABLE', 'path': ['createLabel'], 'locations': [{'line': 2, 'column': 5}], 'message': 'Repository was archived so is read-only'}]
Error: Process completed with exit code 1.
```
https://github.com/figuren-theater/.github/actions/runs/5424170871/jobs/9863140119

Is there anything I can do, to prevent this error? 
Would be great to read your opinion on this.

**Comment by carstingaxion** [comment]
Hi @mefellows and thank you for committing your fixed fork. 👍

**Comment by mefellows** [comment]
You're welcome! Apologies I did plan on re-contributing back the fix if it addressed it - want me to send a PR through or have you taken it on board?

**Comment by carstingaxion** [comment]
> want me to send a PR through 

This would be nice, but I assume, we both are not allowed to open a PR, without being a *collaborator*. 
But hopefully @mbestavros will take this into account and merge the fix soon.

> or have you taken it on board?

I'm going to use your repo for now, lets see for how long ;)

**Comment by carstingaxion** [comment]
:+1: Tested and worked like a charm.

![grafik](https://github.com/actions-automation/manage-your-labels/assets/198883/c41553dc-5ff7-4600-8035-1c4fea278c32)

**Comment by mefellows** [comment]
Thanks, glad it's working for you! I've just opened a PR to this repo in case the change is acceptable to the author.

**Comment by mbestavros** [comment]
Hey @carstingaxion and @mefellows - apologies for the radio silence! This issue and accompanying PR were lost in my inbox, but thank you so much for the contribution. I'll look it over and likely merge it!

**Comment by carstingaxion** [comment]
Hey @mbestavros, long time ago, but I wanted to come back and Thank you! 

Great you merged the provided fix.
